/**
 * Distil Chromium's Lens protos into a typed table of field numbers.
 *
 * A full protobuf runtime costs about 24 kB gzipped for this schema, because
 * the descriptors it needs at runtime cannot be tree-shaken. That is a lot for
 * a userscript that parses on every page load. But hand-writing field numbers
 * into the codec is how they quietly go stale.
 *
 * So: the descriptors are read here, at build time, and reduced to constants.
 * The bundle gets the numbers without the runtime, and `bun run gen` re-syncs
 * them whenever proto/ is refreshed from Chromium.
 *
 * Usage: bun run gen
 */

import { readdir, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { DescFile, DescMessage } from '@bufbuild/protobuf';

const GEN_DIR = new URL('../.protogen/', import.meta.url);
const OUT_FILE = new URL('../src/gen/fields.ts', import.meta.url);

/** Messages we actually touch. Everything else would be dead weight. */
const WANTED = new Set([
  'LensOverlayServerRequest',
  'LensOverlayServerResponse',
  'LensOverlayServerError',
  'LensOverlayObjectsRequest',
  'LensOverlayObjectsResponse',
  'LensOverlayRequestContext',
  'LensOverlayRequestId',
  'LensOverlayClientContext',
  'LocaleContext',
  'RenderingContext',
  'AppliedFilters',
  'AppliedFilter',
  'AppliedFilter_Translate',
  'ImageData',
  'ImagePayload',
  'ImageMetadata',
  'Text',
  'TextLayout',
  'TextLayout_Word',
  'TextLayout_Word_FormulaMetadata',
  'TextLayout_Line',
  'TextLayout_Paragraph',
  'Geometry',
  'CenterRotatedBox',
  'DeepGleamData',
  'TranslationData',
  'TranslationData_Status',
  'TranslationData_TextStyle',
  'TranslationData_BackgroundImageData',
  'TranslationData_Line',
  'TranslationData_Line_Word',
]);

function collect(message: DescMessage, into: Map<string, Map<string, number>>): void {
  const key = message.typeName.split('.').pop() ?? message.name;
  const flattened = message.typeName.replace(/^lens\./, '').replace(/\./g, '_');
  const name = WANTED.has(flattened) ? flattened : WANTED.has(key) ? key : null;

  if (name) {
    const fields = new Map<string, number>();
    for (const field of message.fields) fields.set(field.localName, field.number);
    into.set(name, fields);
  }
  for (const nested of message.nestedMessages) collect(nested, into);
}

function render(tables: Map<string, Map<string, number>>): string {
  const lines: string[] = [
    '// Generated by scripts/gen-fields.ts from proto/. Do not edit by hand.',
    '// Re-run `bun run gen` after refreshing proto/ from Chromium.',
    '',
    '/** Protobuf field numbers, keyed by message then by field. */',
    'export const F = {',
  ];
  for (const [message, fields] of [...tables].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${message}: {`);
    for (const [field, number] of fields) lines.push(`    ${field}: ${number},`);
    lines.push('  },');
  }
  lines.push('} as const;', '');
  lines.push('export type FieldTable = typeof F;', '');
  return lines.join('\n');
}

const genDir = fileURLToPath(GEN_DIR);
const entries = await readdir(genDir);
const tables = new Map<string, Map<string, number>>();

for (const entry of entries) {
  if (!entry.endsWith('_pb.ts')) continue;
  const module: Record<string, unknown> = await import(pathToFileURL(join(genDir, entry)).href);
  for (const value of Object.values(module)) {
    // Every generated file exports exactly one `file_*` descriptor.
    const file = value as DescFile | undefined;
    if (!file || typeof file !== 'object' || !('messages' in file)) continue;
    for (const message of file.messages) collect(message, tables);
  }
}

if (!tables.size) throw new Error('No descriptors found. Run `bunx buf generate` first.');

await mkdir(new URL('../src/gen/', import.meta.url), { recursive: true });
await writeFile(OUT_FILE, render(tables), 'utf8');

const fieldCount = [...tables.values()].reduce((n, m) => n + m.size, 0);
console.log(`Wrote src/gen/fields.ts: ${tables.size} messages, ${fieldCount} fields.`);
